version: '3'

services:
  iscc-service:
    image: titusz/iscc-service:0.1.6
    restart: unless-stopped
    env_file:
      - iscc-service.env
    ports:
      - 8000:8080
  iscc-demo:
    image: iscc-demo
    build:
      context: .
      dockerfile: .ci/Dockerfile
    restart: unless-stopped
    depends_on:
      - iscc-service
    ports:
      - 8080:80
